### ISSUE TITLE
Purpose of this project

### ISSUE THREAD

**Issue by gagan-bansal** [bigeasy/indexeddb#20]
Hey, I was looking for indexedDB simple API and found this project. Would you please elaborate the purpose of this project as it seems a lot work is going on here. I mean how its different from other packages like idb or localForage.

If in case it's too early to describe and you are busy in work, please ignore my question.

**Comment by codebling** [comment]
Not the author, but my impression is that it is an implementation of IndexedDB outside of the browser. There are a number of packages that replicate functionality of Node.js for use in the browser and the functionality of the browser for use in Node.js. These packages make it easier to write code that can run in both Node.js and in the browser.

**Comment by gagan-bansal** [comment]
@codebling thank you for update. I got your point.
